# Generated by Django 2.0 on 2018-07-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名次')),
                ('note', models.TextField(verbose_name='班级介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('address', models.TextField(verbose_name='地址')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='学生班级', to='helloworld.Klass')),
            ],
        ),
    ]
